name: NodeJS with vite build + Publish to Comfy registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'jtydhr88' }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Publish Custom Node
      uses: Comfy-Org/publish-node-action@main
      with:
        personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        skip_checkout: 'true'
